# exports/pdf_exporter.py

import os
from fpdf import FPDF

class MeetInsightPDF(FPDF):
    def header(self):
        # Draw header banner or line
        self.set_fill_color(88, 12, 60) # Brand Wine color (#580c3c)
        self.rect(0, 0, 210, 10, 'F')
        self.set_y(15)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by MeetInsight', 0, 0, 'C')

def clean_text(text: str) -> str:
    """Sanitize strings to avoid FPDF character set exceptions with default fonts."""
    if not isinstance(text, str):
        return str(text)
    replacements = {
        "\u2014": "-",   # em-dash
        "\u2013": "-",   # en-dash
        "\u201c": '"',   # left curly double quote
        "\u201d": '"',   # right curly double quote
        "\u2018": "'",   # left curly single quote
        "\u2019": "'",   # right curly single quote
        "\u2022": "*",   # bullet
        "\u00a0": " ",   # non-breaking space
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    # Encode as latin-1, replacing any characters that can't be represented
    return text.encode("latin-1", "replace").decode("latin-1")

def generate_pdf_report(report_data: dict, output_path: str) -> str:
    """
    Generates a high-quality PDF report from the meeting intelligence data.
    
    Args:
        report_data (dict): The complete meeting report dictionary.
        output_path (str): Filepath to save the generated PDF.
        
    Returns:
        str: Absolute path to the PDF.
    """
    meta = report_data.get("metadata", {})
    brief = report_data.get("brief", {})
    decisions = report_data.get("decisions", [])
    actions = report_data.get("action_items", [])
    risks = report_data.get("risks", [])
    changes = report_data.get("changes", [])
    questions = report_data.get("questions", [])
    
    pdf = MeetInsightPDF(orientation='P', unit='mm', format='A4')
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    
    # Title Section
    pdf.set_text_color(88, 12, 60) # Wine
    pdf.set_font('helvetica', 'B', 24)
    pdf.cell(0, 12, clean_text(meta.get("title", "Meeting Report")), ln=True)
    pdf.ln(2)
    
    # Metadata Row
    pdf.set_text_color(80, 80, 80)
    pdf.set_font('helvetica', '', 9)
    metadata_text = f"Date: {meta.get('date', 'N/A')} | Time: {meta.get('time', 'N/A')} | Duration: {meta.get('duration', 'N/A')} | Speakers: {meta.get('speakers_count', 0)}"
    pdf.cell(0, 5, clean_text(metadata_text), ln=True)
    
    # Divider
    pdf.set_draw_color(220, 220, 220)
    pdf.line(10, pdf.get_y() + 2, 200, pdf.get_y() + 2)
    pdf.ln(5)
    
    # 60-Second Brief
    pdf.set_text_color(88, 12, 60)
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 8, "THE 60-SECOND BRIEF", ln=True)
    pdf.ln(1)
    
    pdf.set_text_color(40, 40, 40)
    pdf.set_font('helvetica', '', 10)
    summary_text = brief.get("summary", "").replace("**", "") # Remove markdown bolding for PDF
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, clean_text(summary_text))
    pdf.ln(4)
    
    # Tags
    tags = brief.get("tags", [])
    if tags:
        pdf.set_font('helvetica', 'I', 9)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, clean_text(f"Keywords: {', '.join(tags)}"), ln=True)
        pdf.ln(4)
        
    # Decisions Section
    if decisions:
        pdf.set_text_color(88, 12, 60)
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 8, f"Key Decisions ({len(decisions)})", ln=True)
        pdf.ln(1)
        
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(40, 40, 40)
        for idx, d in enumerate(decisions, 1):
            decision_desc = f"{idx}. {d.get('text', '')} (Owner: {d.get('speaker', 'Team')} | {d.get('timestamp', '00:00')} | Impact: {d.get('impact', 'Medium')})"
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, clean_text(decision_desc))
            pdf.ln(1)
        pdf.ln(3)
        
    # Action Items Section
    if actions:
        pdf.set_text_color(88, 12, 60)
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 8, f"Action Items ({len(actions)})", ln=True)
        pdf.ln(1)
        
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(40, 40, 40)
        for idx, a in enumerate(actions, 1):
            status = "[X]" if a.get("completed") else "[ ]"
            action_desc = f"{status} {idx}. {a.get('text', '')} (Assignee: {a.get('assignee', 'Unassigned')} | {a.get('due_date', 'TBD')} | Priority: {a.get('priority', 'Medium')})"
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, clean_text(action_desc))
            pdf.ln(1)
        pdf.ln(3)
        
    # Risks Section
    if risks:
        pdf.set_text_color(88, 12, 60)
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 8, f"Risks & Blockers ({len(risks)})", ln=True)
        pdf.ln(1)
        
        for idx, r in enumerate(risks, 1):
            pdf.set_text_color(40, 40, 40)
            pdf.set_font('helvetica', 'B', 10)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, clean_text(f"{idx}. {r.get('title', '')} (Impact: {r.get('impact', 'Medium')})"))
            
            pdf.set_font('helvetica', '', 10)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, clean_text(f"   {r.get('description', '')}"))
            pdf.ln(1)
        pdf.ln(3)
        
    # Change Requests Section
    if changes:
        pdf.set_text_color(88, 12, 60)
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 8, f"Change Requests ({len(changes)})", ln=True)
        pdf.ln(1)
        
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(40, 40, 40)
        for idx, c in enumerate(changes, 1):
            change_desc = f"{idx}. {c.get('title', '')} (Requested by: {c.get('requestor', 'N/A')} | Timestamp: {c.get('timestamp', 'N/A')} | Priority: {c.get('priority', 'P2')})"
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, clean_text(change_desc))
            pdf.ln(1)
        pdf.ln(3)
        
    # Open Questions Section
    if questions:
        pdf.set_text_color(88, 12, 60)
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 8, f"Open Questions ({len(questions)})", ln=True)
        pdf.ln(1)
        
        pdf.set_font('helvetica', 'I', 10)
        pdf.set_text_color(40, 40, 40)
        for idx, q in enumerate(questions, 1):
            ques_desc = f"{idx}. \"{q.get('text', '')}\" — asked by {q.get('speaker', 'N/A')}"
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, clean_text(ques_desc))
            pdf.ln(1)
        pdf.ln(3)
        
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return os.path.abspath(output_path)
